### ISSUE TITLE
Triggering dynamic load for Activities causes earlier Activity formatting to break

### ISSUE THREAD

**Issue by zhulov3rz** [SchoolIdolTomodachi/CinderellaProducers#11]
If you trigger the infinite scrolling feature that causes more activities to load, the formatting in already-loaded posts break.

Repro:
1. Find a formatted post on the home page
2. Scroll down until the page attempts to load more Activities 
3. Scroll back to the formatted post, the formatting should now be gone.

Video/Showcase of Issue:
https://youtu.be/xdk8iAHtj_Y

**Comment by zhulov3rz** [comment]
I'd like to add that if the formatted post was loaded by a dynamic in-page load, it's formatted fine.
However, the next dynamic load you trigger will mess up the formatting.

**Comment by db0company** [comment]
Thanks for reporting this!

Fixed in https://github.com/SchoolIdolTomodachi/MagiCircles/commit/72933d101e6550165c7f881509307b6607fafe31
