### ISSUE TITLE
Glitch with certain letter combination in description typing

### ISSUE THREAD

**Issue by CatKid12** [SchoolIdolTomodachi/CinderellaProducers#2]
While typing, 'i' turns into 'fi' when adding an 'f', rather than 'if'. 
Have not yet discovered if it is the same for other combinations.
Also thank you for the beta! Looking great so far!
![img_7897](https://cloud.githubusercontent.com/assets/22424695/18813529/0b543f38-82f5-11e6-857e-151dc55cee44.JPG)
![img_7898](https://cloud.githubusercontent.com/assets/22424695/18813530/0b776e0e-82f5-11e6-83c6-330a740cbb2e.JPG)

**Comment by db0company** [comment]
Couldn't reproduce. I'm guessing this comes from your browser, you might have a chrome extension or else that does that, or an issue with your keyboard. There isn't any kind of weird javascript here that would cause that behavior.

Thanks for your input though.
